name: SpeechImpact CI/CD - On push to to origin/develop
on:
  push:
    branches:
      - 'main'
env:
  AWS_S3_BUCKET: 'nguyengiason'
  AWS_ACESS_KEY_ID: ${{secrets.AWS_ACESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: 'ap-southeast-1'

jobs:
  ci:
    name: Keycloak Build Artifact
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Getting yarn cache directory patch
        id: yarn-cache-dir-patch
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          patch: ${{steps.yarn-cache-dir-patch.outputs.dir}}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-yarn-

      - name: Install Dependencies
        run: yarn install --prefer-offline

      - name: SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Build
        run: yarn build

      - name: Build keycloak kcapp
        run: yarn build-keycloak-theme

  build-kc-S3:
    name: Deploy KCApp application
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Upload to S3
        run: |
          aws s3 sync build_keycloak/target/speech-impact-webapp-keycloak-theme-4.4.14.jar s3://nguyengiason/

      # - name: Restart k8s
      #   run: |
      #     kubectl rollout restart deployment/${{secrets.K8S_DEPLOYMENT_NAME}}

      - name: Deploy S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: 'build_keycloak/target/speech-impact-webapp-keycloak-theme-4.4.14.jar'
